steps:
  - name: node
    entrypoint: yarn
    args: ["install"]
  - name: node
    entrypoint: yarn
    args: ["add", "firebase-tools"]
  - name: node
    entrypoint: yarn
    args: ["build"]
  - name: node
    entrypoint: "./node_modules/.bin/firebase"
    args:
      [
        "target:apply",
        "--project",
        "$PROJECT_ID",
        "--token",
        "$_TOKEN",
        "hosting",
        "$BRANCH_NAME",
        "$_SITE_ID",
      ]  
  - name: node
    entrypoint: "./node_modules/.bin/firebase"
    args:
      [
        "deploy",
        "--project",
        "$PROJECT_ID",
        "--token",
        "$_TOKEN",
        "--only",
        "hosting:$BRANCH_NAME",
      ]
